### ISSUE TITLE
flow-control-test.js & loop-test.js error

### ISSUE THREAD

**Issue by ejdelrio** [learn-co-curriculum/js-beatles-loops-lab#14]
In the test for the flow control lab and intro to looping, there are errors in the test file. 

The test flow errors are 
`  describe('switchAge', () => {
    it('should return "You are a teenager" if age is between 13-19', () => {
      expect(switchAge(15)).toEqual("You are a teenager")
    })

    it('should return **"You are not a teenager"** if age not between 13-19', () => {
      expect(switchAge(75)).toEqual(**"You have an age"**)
      expect(switchAge(7)).toEqual(**"You have an age"**)
    })
  })
})`

Where the it says it should return "You are not a teenager" but actually expects "You have an age"

As for the loop test, the doWhileLoop function instead of assessing

(array.length >0 || maybeTrue() = false) 

it seems to be assessing 

(array.length >0 && maybeTrue() = false)

where it sometimes will pass the test or fail. Where it expects the test to have a length of (l-1), it throws an error stating:

`AssertionError: expected [] to have a length at most -1 but got 0`

Where it expects a length of -1 instead of 0.

**Comment by JessRudder** [comment]
This is not for this lab.  Issue has been addressed on other lab though.
