### ISSUE TITLE
Beatles loop error typo

### ISSUE THREAD

**Issue by mckinney99** [learn-co-curriculum/js-beatles-loops-lab#18]
Unless I'm misreading this (which is easy to do in this lesson) I believe there is a typo in the error message...

1) Beatles Loops returns an array of strings containing what **instruments each instrument** plays:
   
Should be:

1) Beatles Loops returns an array of strings containing what **instruments each musician** plays:

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
