### ISSUE TITLE
learn and learn-b directory doesn't appear to have any specs in it

### ISSUE THREAD

**Issue by foxmic** [learn-co-curriculum/js-beatles-loops-lab#2]
Hi there,

I get the following message when running "learn" and "learn -b" on **Nitrous**:

➜  js-beatles-loops-lab-v-000 git:(master) ✗ learn
This directory doesn't appear to have any specs in it.

**Comment by pletcher** [comment]
Please update your learn gem (`gem update learn-co`). `learn-test --version` needs to print at least `2.3.0`.

**Comment by foxmic** [comment]
My learn gem was updated. Version 2.3.1
Still not working.

On Sat, May 14, 2016 at 6:41 AM, Charles Pletcher notifications@github.com
wrote:

> Please update your learn gem (gem update learn-co). learn-test --version
> needs to print at least 2.3.0.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/js-beatles-loops-lab/issues/2#issuecomment-219153860

## 

Michel Fuchs

South Yarra VIC 3141
michelfuchs0@gmail.com

**Comment by pletcher** [comment]
Are you still getting the error "This directory doesn't appear to have any specs in it"? Are there any other errors?

Could you try closing your terminal and reopening it? (There are some hooks that get triggered on a new session.)

And can you successfully run `npm test` in the directory? (You might need to run `npm install` first.)

**Comment by foxmic** [comment]
Hi Charles

Thanks for your answer! The error "This directory doesn't appear to have
any specs in it" appears on my nitrous (only error message). When I run it
on the learn ILE on my mac I get the following error messages. Because of
these erros I moved on with my track. But now I am getting the same erros
at the "JS Hoisting Lab".

_WHEN I RUN learn:_

// ♥ learn

> js-beatles-loops-lab@0.1.0 test
> /home/foxmic/code/labs/js-beatles-loops-lab-v-
> 000
> 
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

/home/foxmic/code/labs/js-beatles-loops-lab-v-000/test/beatles-test.js:5

const expect = require('chai').expect

^^^^^
SyntaxError: Use of const in strict mode.

```
at Module._compile (module.js:439:25)

at Object.Module._extensions..js (module.js:474:10)

at Module.load (module.js:356:32)

at Function.Module._load (module.js:312:12)

at Module.require (module.js:364:17)

at require (module.js:380:17)

at
```

/home/foxmic/code/labs/js-beatles-loops-lab-v-000/node_modules/mocha/lib/
mocha.js:219:27

```
at Array.forEach (native)

at Mocha.loadFiles
```

(/home/foxmic/code/labs/js-beatles-loops-lab-v-000/node_m
odules/mocha/lib/mocha.js:216:14)

```
at Mocha.run
```

(/home/foxmic/code/labs/js-beatles-loops-lab-v-000/node_modules
/mocha/lib/mocha.js:468:10)

```
at Object.<anonymous>
```

(/home/foxmic/code/labs/js-beatles-loops-lab-v-000/nod
e_modules/mocha/bin/_mocha:403:18)

```
at Module._compile (module.js:456:26)

at Object.Module._extensions..js (module.js:474:10)

at Module.load (module.js:356:32)

at Function.Module._load (module.js:312:12)

at Function.Module.runMain (module.js:497:10)

at startup (node.js:119:16)

at node.js:902:3
```

npm ERR! weird error 8

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read

/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

/usr/local/rvm/gems/ruby-2.2.3/gems/learn-test-2.3.1/lib/learn_test/strategies/m
ocha.rb:48:in `results': undefined method`[]' for nil:NilClass
(NoMethodError)
        from
/usr/local/rvm/gems/ruby-2.2.3/gems/learn-test-2.3.1/lib/learn_test
/runner.rb:60:in `block in push_results'
        from
/usr/local/rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/conne
ction.rb:388:in`block in build_request'

```
    from
```

/usr/local/rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/reque
st.rb:26:in `block in create'

```
    from
```

/usr/local/rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/reque
st.rb:25:in `tap'

```
    from
```

/usr/local/rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/reque
st.rb:25:in `create'

```
    from
```

/usr/local/rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/conne
ction.rb:384:in `build_request'
        from
/usr/local/rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/conne
ction.rb:370:in`run_request'

```
    from
```

/usr/local/rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/conne
ction.rb:177:in `post'

```
    from
```

/usr/local/rvm/gems/ruby-2.2.3/gems/learn-test-2.3.1/lib/learn_test
/runner.rb:57:in `push_results'

```
    from
```

/usr/local/rvm/gems/ruby-2.2.3/gems/learn-test-2.3.1/lib/learn_test
/runner.rb:17:in `run'

```
    from
```

/usr/local/rvm/gems/ruby-2.2.3/gems/learn-test-2.3.1/bin/learn-test
:56:in `<top (required)>'

```
    from /usr/local/rvm/gems/ruby-2.2.3/bin/learn-test:23:in `load'

    from /usr/local/rvm/gems/ruby-2.2.3/bin/learn-test:23:in `<main>'

    from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in
```

`eva
l'

```
    from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in
```

`<ma
in>'

_WHEN I RUN npm test:_

[08:10:40](master) js-beatles-loops-lab-v-000

// ♥ npm install

[08:10:53](master) js-beatles-loops-lab-v-000

// ♥ npm test

> js-beatles-loops-lab@0.1.0 test
> /home/foxmic/code/labs/js-beatles-loops-lab-v-
> 000
> 000
> 
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

/home/foxmic/code/labs/js-beatles-loops-lab-v-000/test/beatles-test.js:5

const expect = require('chai').expect

^^^^^

SyntaxError: Use of const in strict mode.

```
at Module._compile (module.js:439:25)

at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)

at Function.Module._load (module.js:312:12)

at Module.require (module.js:364:17)

at require (module.js:380:17)

at
```

/home/foxmic/code/labs/js-beatles-loops-lab-v-000/node_modules/mocha/lib/
mocha.js:219:27

```
at Array.forEach (native)

at Mocha.loadFiles
```

(/home/foxmic/code/labs/js-beatles-loops-lab-v-000/node_m
odules/mocha/lib/mocha.js:216:14)

```
at Mocha.run
```

(/home/foxmic/code/labs/js-beatles-loops-lab-v-000/node_modules
/mocha/lib/mocha.js:468:10)

```
at Object.<anonymous>
```

(/home/foxmic/code/labs/js-beatles-loops-lab-v-000/nod
e_modules/mocha/bin/_mocha:403:18)

```
at Module._compile (module.js:456:26)

at Object.Module._extensions..js (module.js:474:10)

at Module.load (module.js:356:32)

at Function.Module._load (module.js:312:12)

at Function.Module.runMain (module.js:497:10)

at startup (node.js:119:16)

at node.js:902:3
```

npm ERR! weird error 8

npm WARN This failure might be due to the use of legacy binary "node"

npm WARN For further explanations, please read

/usr/share/doc/nodejs/README.Debian

On Wed, May 18, 2016 at 2:12 AM, Charles Pletcher notifications@github.com
wrote:

> Are you still getting the error "This directory doesn't appear to have any
> specs in it"? Are there any other errors?
> 
> Could you try closing your terminal and reopening it? (There are some
> hooks that get triggered on a new session.)
> 
> And can you successfully run npm test in the directory? (You might need
> to run npm install first.)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/js-beatles-loops-lab/issues/2#issuecomment-219769126

## 

Michel Fuchs

South Yarra VIC 3141
michelfuchs0@gmail.com

**Comment by pletcher** [comment]
Ah, okay. The IDE's remote environment is running an old version of Node.js. I'll work on getting that updated ASAP.

Out of curiosity, have you tried setting up the environment locally on your Mac? You can just install Node.js (`brew install node`) and `n` (or another package manager -- but I like n) (`npm install -g n`).

Then just run `n 6.1.0`, cd into the lesson, `npm install` and `npm test`. If _that_ works, we can work on getting submit working (which requires Ruby and is a bit more of a pain).

**Comment by foxmic** [comment]
Hi Charles

Ok thanks! Would be great if you get that updated asap!

No I haven't tried setting up the environment locally because I'll get a
new MacBook soon. So I think I wait with doing this until I get the new
one. I'll use your instructions then, thank you!

On Wed, May 18, 2016 at 9:09 AM, Charles Pletcher notifications@github.com
wrote:

> Ah, okay. The IDE's remote environment is running an old version of
> Node.js. I'll work on getting that updated ASAP.
> 
> Out of curiosity, have you tried setting up the environment locally on
> your Mac? You can just install Node.js (brew install node) and n (or
> another package manager -- but I like n) (npm install -g n).
> 
> Then just run n 6.1.0, cd into the lesson, npm install and npm test. If
> _that_ works, we can work on getting submit working (which requires Ruby
> and is a bit more of a pain).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/js-beatles-loops-lab/issues/2#issuecomment-219880868

## 

Michel Fuchs

South Yarra VIC 3141
michelfuchs0@gmail.com

**Comment by foxmic** [comment]
Hi Charles,

Any news about the update of Node.js?

Thanks and kind regards,
Michel

On Wed, May 18, 2016 at 9:48 AM, Michel Fuchs michelfuchs0@gmail.com
wrote:

> Hi Charles
> 
> Ok thanks! Would be great if you get that updated asap!
> 
> No I haven't tried setting up the environment locally because I'll get a
> new MacBook soon. So I think I wait with doing this until I get the new
> one. I'll use your instructions then, thank you!
> 
> On Wed, May 18, 2016 at 9:09 AM, Charles Pletcher <
> notifications@github.com> wrote:
> 
> > Ah, okay. The IDE's remote environment is running an old version of
> > Node.js. I'll work on getting that updated ASAP.
> > 
> > Out of curiosity, have you tried setting up the environment locally on
> > your Mac? You can just install Node.js (brew install node) and n (or
> > another package manager -- but I like n) (npm install -g n).
> > 
> > Then just run n 6.1.0, cd into the lesson, npm install and npm test. If
> > _that_ works, we can work on getting submit working (which requires Ruby
> > and is a bit more of a pain).
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/learn-co-curriculum/js-beatles-loops-lab/issues/2#issuecomment-219880868
> 
> ## 
> 
> Michel Fuchs
> 
> South Yarra VIC 3141
> michelfuchs0@gmail.com

## 

Michel Fuchs

South Yarra VIC 3141
michelfuchs0@gmail.com

**Comment by pletcher** [comment]
Hi Michel,

You should be good to go!

Thanks,
Charles

**Comment by foxmic** [comment]
Thanks for your help Charles!

On Fri, May 20, 2016 at 8:27 AM, Charles Pletcher notifications@github.com
wrote:

> Hi Michel,
> 
> You should be good to go!
> 
> Thanks,
> Charles
> 
> On Wednesday, May 18, 2016, foxmic notifications@github.com wrote:
> 
> > Hi Charles,
> > 
> > Any news about the update of Node.js?
> > 
> > Thanks and kind regards,
> > Michel
> > 
> > On Wed, May 18, 2016 at 9:48 AM, Michel Fuchs <michelfuchs0@gmail.com
> > <javascript:_e(%7B%7D,'cvml','michelfuchs0@gmail.com');>>
> > wrote:
> > 
> > > Hi Charles
> > > 
> > > Ok thanks! Would be great if you get that updated asap!
> > > 
> > > No I haven't tried setting up the environment locally because I'll get
> > > a
> > > new MacBook soon. So I think I wait with doing this until I get the new
> > > one. I'll use your instructions then, thank you!
> > > 
> > > On Wed, May 18, 2016 at 9:09 AM, Charles Pletcher <
> > > notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > 
> > > > Ah, okay. The IDE's remote environment is running an old version of
> > > > Node.js. I'll work on getting that updated ASAP.
> > > > 
> > > > Out of curiosity, have you tried setting up the environment locally on
> > > > your Mac? You can just install Node.js (brew install node) and n (or
> > > > another package manager -- but I like n) (npm install -g n).
> > > > 
> > > > Then just run n 6.1.0, cd into the lesson, npm install and npm test.
> > > > If
> > > > _that_ works, we can work on getting submit working (which requires
> > > > Ruby
> > > > and is a bit more of a pain).
> > > > 
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/learn-co-curriculum/js-beatles-loops-lab/issues/2#issuecomment-219880868
> > 
> > > ## 
> > > 
> > > Michel Fuchs
> > > 
> > > South Yarra VIC 3141
> > > michelfuchs0@gmail.com
> > > <javascript:_e(%7B%7D,'cvml','michelfuchs0@gmail.com');>
> > 
> > ## 
> > 
> > Michel Fuchs
> > 
> > South Yarra VIC 3141
> > michelfuchs0@gmail.com
> > <javascript:_e(%7B%7D,'cvml','michelfuchs0@gmail.com');>
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/learn-co-curriculum/js-beatles-loops-lab/issues/2#issuecomment-220170242
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/js-beatles-loops-lab/issues/2#issuecomment-220463177

## 

Michel Fuchs

South Yarra VIC 3141
michelfuchs0@gmail.com
