### ISSUE TITLE
Confusing Text

### ISSUE THREAD

**Issue by JordanTreDaniel** [learn-co-curriculum/js-beatles-loops-lab#23]
The instructions for the first test are confusing; I had to look at the test in order to see what was actually required of me.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
