### ISSUE TITLE
IDE not working

### ISSUE THREAD

**Issue by EdPutans** [learn-co-curriculum/js-beatles-loops-lab#27]
Clicking on the IDE button doesn't do anything on any of my devices. Not in the OG chrome, not in chromium. 
Before this, when I got into the IDE all of the labs' files were gone with only the file I am working in present. Commands were unable to execute with an error popping in the lines of "This directory doesn't appear to have any specs in it." When restarting the files appeared for a brief moment and vanished again.
resetting the lab according to the youtube tutorial didn't work as commands don't go through.
It started when I lost connection for a second. Now it looks like a user account issue.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub][raise] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.). If Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
