### ISSUE TITLE
unable to fork the lesson

### ISSUE THREAD

**Issue by varsil123** [learn-co-curriculum/js-beatles-loops-lab#39]
i have been unable to fork a lesson for a few days.
i manually fork it in the downloadable IDE
however, i have been having problem testing for the past few attempts
please reach out to me with any help possible 
i have also contacted support@learn.com

**Comment by maxwellbenton** [comment]
Hi @varsil123,

Thank you for reaching out. Unfortunately, I am unable to replicate this issue currently. support@learn.com is the best place to reach out to for this sort of error. This issue can also be raised to the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) team, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

We apologize for any frustration this has caused, but appreciate your feedback!
