### ISSUE TITLE
Github not receiving updates from completed/submitted prep work

### ISSUE THREAD

**Issue by zabrivera** [learn-co-curriculum/js-beatles-loops-lab#40]
![SubmittedWithBrowserIDE](https://user-images.githubusercontent.com/56931633/72313837-a9af0e80-365a-11ea-80d1-bd2b940521a5.jpg)

I submitted labs with both browser Learn IDE and local Learn IDE, no dice. Still doesn't update Github. Additionally, it seems to be affecting the "Consecutive Days" counter in the Dashboard `https://learn.co/tracks/bootcamp-prep-v2`

Confirmed that my Github account was properly added to the Account --> Connected Services section.

**Comment by maxwellbenton** [comment]
Hi @zabrivera,

Thank you for reaching out. Unfortunately, I am unable to replicate this issue on my end.

GitHub issues are typically reserved for problems with the curriculum content. While we do actively review and resolve issues reported on Learn repositories, for bugs in the Learn platform or tools, please reach out to support@learn.co.

This issue would also be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

We apologize for any frustration this has caused, but appreciate your feedback!
