### ISSUE TITLE
Compiler issues

### ISSUE THREAD

**Issue by hock478** [learn-co-curriculum/js-beatles-loops-lab#42]
Compiler stops me from typing commands after first try.

**Comment by maxwellbenton** [comment]
Hi @hock478,

Thank you for reaching out. Unfortunately, I am unable to replicate this issue currently. 

GitHub issues are typically reserved for problems with the curriculum content. For bugs in the Learn platform or tools, please reach out to support@learn.co.

This issue can also be raised to the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) team, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

We apologize for any frustration this has caused, but appreciate your feedback!
