### ISSUE TITLE
problem needs to be clarified, preferably with examples

### ISSUE THREAD

**Issue by catherineluse** [learn-co-curriculum/js-beatles-loops-lab#7]
Here's the original problem which I think is unclear: 

> Create a function iLoveTheBeatles which accepts a number as a parameter. The body of the function should create a variable that stores an empty array. Then, implement a do-while loop inside the function that adds "I love the Beatles!" to the empty array. Then the loop should increment the number passed in as a parameter. The condition of the loop should check to see that the parameter number is less than 15. The function should return the array with the strings "I love the Beatles!".

This wording is confusing because it describes how your function should work instead of what it has to produce as the output. It never explicitly says that your output should contain at least one console.log statement and up to 15 console.log statements. It never says what the function is supposed to return if the parameter is greater than 15. Please clarify.

**Comment by catherineluse** [comment]
> The condition of the loop should check to see that the parameter number is less than 15.

So you are only supposed to print console.log 15 times? Or you are supposed to not print console.log for any input parameter more than 15? I wish it was clear.

**Comment by catherineluse** [comment]
I just passed the tests for this problem. After solving it, I can say it would be clearer it says that the array needs to contain a number of strings that represents the difference between the input number and 15. So if the input is -30, the array will have 45 strings.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
