### ISSUE TITLE
I can see notifications for all kinds of messages, but not the message itself

### ISSUE THREAD

**Issue by catherineluse** [learn-co-curriculum/js-beatles-loops-lab#8]
About once every five minutes I get a notification "John says this" or "David asked a question." I constantly hear the message noise. But once it's got my attention, the message disappears and I can't find it.

It gets extremely irritating over time to be distracted by notifications without the ability to find, read or respond to the messages. It seems like I can hear the notifications no matter where I am, but I can only see the message if I happen to be on the right page or have the right window open.

**Comment by JessRudder** [comment]
Hi @catherineluse if you are using Learn in Chrome, you can right click on the tab and choose to mute it.  For more information about how to find the questions, I suggest using the "Ask a Question" feature to talk to a Learn Expert.  This is for specific issues on a given lab.
